apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-microservice
  labels:
    app: profile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profile
  template:
    metadata:
      labels:
        app: profile
    spec:
      containers:
        - name: profile
          image: microservicesproject:latest
          imagePullPolicy: Never
          ports:
          - containerPort: 8080