apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-microservice
  labels:
    app: profile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profile
  template:
    metadata:
      labels:
        app: profile
    spec:
      containers:
        - name: profile-database
          image: mcr.microsoft.com/mssql/server:2022-latest
          ports:
            - containerPort: 4000
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              value: "Password123!"  # Change this to a strong password
            - name: MSSQL_TCP_PORT
              value: "4000"
        - name: profile
          image: docker.io/library/profile-microservice:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
